src/Entity/Cast.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;

/**
 * @ORM\Entity(repositoryClass="App\Repository\CastRepository")
 */
class Cast
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     * @Groups({"serie:details"})
     */
    private $tmdb_id;

     /**
     * @ORM\Column(type="string")
     * @ORM\Column(name="protagonist")
     * @Groups({"serie:details"})
     */
    private $protagonist;

    /**
     * @ORM\Column(type="datetime")
     * @Groups({"serie:details"})
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updated_at;


    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Serie", inversedBy="cast")
     * @ORM\JoinColumn(nullable=false)
     */
    private $serie;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Actor", mappedBy="casts", cascade={"persist"})
     * @Groups({"serie:details"})
     */
    private $actors;

    public function __construct()
    {
        $this->actors = new ArrayCollection();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTmdbId(): ?int
    {
        return $this->tmdb_id;
    }

    public function setTmdbId(int $tmdb_id): self
    {
        $this->tmdb_id = $tmdb_id;

        return $this;
    }

    public function getProtagonist(): ?string
    {
        return $this->protagonist;
    }

    public function setProtagonist(string $protagonist): self
    {
        $this->protagonist = $protagonist;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }


    public function getSerie(): ?Serie
    {
        return $this->serie;
    }

    public function setSerie(?Serie $serie): self
    {
        $this->serie = $serie;

        return $this;
    }

    /**
     * @return Collection|Actor[]
     */
    public function getActors(): Collection
    {
        return $this->actors;
    }

    public function addActor(Actor $actor): self
    {
        if (!$this->actors->contains($actor)) {
            $this->actors[] = $actor;
            $actor->addCast($this);
        }

        return $this;
    }

    public function removeActor(Actor $actor): self
    {
        if ($this->actors->contains($actor)) {
            $this->actors->removeElement($actor);
            $actor->removeCast($this);
        }

        return $this;
    }

}

templates/home/homelist.html.twig
{% extends "base.html.twig" %}
{% block body %}
	
		<h1>Hello ! ✅</h1>

		<hr>
<table>
    <tbody>
        
            {% for serie in seriesTrending %}
                <tr>
                            <td><img src="https://image.tmdb.org/t/p/w500{{serie["poster_path"]}}" alt="Card image cap"></td>
                            <td><h5>{{ serie.name }}</h5></td>
                            <td><p>{{ serie.overview }}</p></td>
                            <td><small>Note : {{ serie["vote_average"] }}</small></td>
                </tr>
            {% endfor %}
            {% for serie in seriesRecent %}
            
                <tr>
                            <td><img  src="https://image.tmdb.org/t/p/w500{{serie["poster_path"]}}" alt="Card image cap"></td>
                            <td><h5>{{ serie.name }}</h5></td>
                            <td><p>{{ serie.overview }}</p></td>
                            <td><small>Note : {{ serie["vote_average"] }}</small></td>
                </tr>
                {% endfor %}
        
    </tbody>
</table>
{% endblock %}

templates/home/list.html.twig
{% extends "base.html.twig" %}
{% block body %}

		<h1>Hello ! ✅</h1>

		<hr>
<table>
    <tbody>
		{% for serie in series %}
                <tr>
                            <td><img src="https://image.tmdb.org/t/p/w500{{serie["poster_path"]}}" alt="Card image cap"></td>
                            <td><h5>{{ serie.name }}</h5></td>
                            <td><p>{{ serie.overview }}</p></td>
                            <td><small>Note : {{ serie.vote_average }}</small></td>
                            <td><small>Note : {{ serie.tmdbId }}</small></td>
                </tr>
                
            {% endfor %}
        
    </tbody>
</table>

{% endblock %}

templates/home/routeListDev.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello MainController!
{% endblock %}

{% block body %}

		<div class="example-wrapper">
			<h1>Hello ! ✅</h1>

			<h2>List des routes de l'api</h2>
			<ul>
				<li>Série par Id : "/tv/show/{serie_id}"</li>
				<li>Série par recherche : "/tv/search/{serie_name}"</li>
				<li>Série par découvertes : "/tv/discover"</li>
				<li>Série par critères : "/tv/discover/standard/{vote_average}/{with_runtime}/{with_genres}/{with_networks}"</li>
			</ul>
		</div>
	{% endblock %}